# Generated by Django 3.2.18 on 2023-04-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile'),
    ]

    operations = [
    ]
